// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "sdt-bicycle-rental/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UserLoginer is an autogenerated mock type for the UserLoginer type
type UserLoginer struct {
	mock.Mock
}

// Login provides a mock function with given fields: email, password
func (_m *UserLoginer) Login(email string, password string) (*models.User, string, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *models.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.User, string, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewUserLoginer creates a new instance of UserLoginer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserLoginer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserLoginer {
	mock := &UserLoginer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
