// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	dto "sdt-bicycle-rental/internal/repository/dto"

	mock "github.com/stretchr/testify/mock"

	models "sdt-bicycle-rental/internal/models"
)

// UserRegisterer is an autogenerated mock type for the UserRegisterer type
type UserRegisterer struct {
	mock.Mock
}

// Register provides a mock function with given fields: user
func (_m *UserRegisterer) Register(user *dto.CreateUser) (*models.User, string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(*dto.CreateUser) (*models.User, string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*dto.CreateUser) *models.User); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*dto.CreateUser) string); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*dto.CreateUser) error); ok {
		r2 = rf(user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewUserRegisterer creates a new instance of UserRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegisterer {
	mock := &UserRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
